#!/bin/sh
tput setab 33
tput setaf 15
tput bold
printf "  "
echo -n "$(pwd | sed 's|/home/antu|~|') "
tput setab 28
tput setaf 15
if [ -d $(pwd)/.git ]
then
        printf " "
	echo -n "($(git branch|grep ^*|sed 's/\*//;s/ //'))"
else
	echo -n ""
fi

tput sgr0
echo -n " "
