#!/bin/sh
tput setab 33
tput setaf 15
tput bold
printf "  "
echo -n "$(pwd | sed 's|/home/antu|~|')"
printf " "
tput setab 28
tput setaf 52
if [ -d $(pwd)/.git ]
then
        printf "  "
	echo -n "($(git branch|grep ^*|sed 's/\*//;s/ //'))"
        printf " "
else
	echo -n ""
fi

tput sgr0
echo -n " "
