#!/bin/sh

# Mimeapp script for adding torrent to transmission-daemon, but will also start the daemon first if not running.

# transmission-daemon sometimes fails to take remote requests in its first moments.

pgrep -x qbittorrent-nox || (qbittorrent-nox -d && notify-send "Starting qbittorrent daemon..." && sleep 3 && pkill -RTMIN+7 i3blocks)

qbittorrent-nox "$@" && notify-send "🔽 Torrent added."
