#!/bin/sh

# i3blocks mail module.
# Displays number of unread mail and an loading icon if updating.
# When clicked, brings up `neomutt`.

case $BLOCK_BUTTON in
	1) "$TERMINAL" -e neomutt ;;
	2) setsid $HOME/.config/mutt/etc/mailsync.sh >/dev/null & ;;
	3) pgrep -x dunst >/dev/null && notify-send "📬 Mail module" "\- Shows unread mail
		- Shows 🔃 if syncing mail
		- Left click opens neomutt
		- Middle click syncs mail" ;;
esac
echo "📬" "$(ls ~/Mail/INBOX/new | wc -l)"
